### ISSUE TITLE
from ruamel.yaml import YAML throws an error

### ISSUE THREAD

**Issue by stsavian** [ZaydH/target_identification#7]
Dear authors,

thanks for your great work, I really enjoyed the tecnical depth of the paper, and I find it very useful to overcome some limitations of the method tracin.

I would like to run your code, however I think there migh be some files missing.
In line 36 of fig01_cifar_vs_mnist/poison/_config.py, the line from ruamel.yaml import YAML throws an error. I have tried to install pyyaml but I think you might have defined a custom class.

Also the documentation seems a bit too essential, and I think it may refer to a previous version of the code.

Are you available to address these issues?

Thanks again,
Stefano

**Comment by ZaydH** [comment]
Hi Stefano,

We do not use `pyyaml`.  We use `ruamel.base`.  To install it, call

`pip3 install ruamel.base==1.0.0`

Thanks,
Zayd

**Comment by stsavian** [comment]
Dear Zayd,

thanks for the prompt response! Indeed by installing ruamel.base the script runs.
For others who might encounter this issue: ruamel base was installed already, but it was not detected by python. 
By installing with pip instead of pip3 the package is now detected.

Thanks,
Stefano

**Comment by ZaydH** [comment]
Glad you were able to get this working.  If you need anything else, feel free to reach out.
